### ISSUE TITLE
2 Bitmasks in IncrementRefreshRegister (Z80.cs) are wrong.

### ISSUE THREAD

**Issue by Prefsmaster** [essenbee/z80emu#3]
the 0b01111111 masks to clear bit 7 (both of them) have a 1 too many (0b011111111)

**Comment by Prefsmaster** [comment]
suggested rewrite:

            var savedMsb = R & 0b1000_0000;
            R = (byte)(((R+steps)&0b0111_1111)|savedMsb);

**Comment by essenbee** [comment]
Thanks for finding this, I will fix asap

**Comment by Prefsmaster** [comment]
You're welcome!

Made my own fix like this:

```
            // get lower 7 bits of R
            var refresh = R & 0b01111111;

            // add steps and remove msb from result
            refresh = (refresh+steps) &0x01111111;

            // update only lower 7 bits of R
            R = (byte) ((R & 0b10000000) | refresh);
```

can also be one line, but I prefer readability.

**Comment by essenbee** [comment]
Fixed and NuGet package updated
